[2025-10-30T12:26:03.279+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:26:03.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:26:03.283+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:26:03.282+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:26:03.300+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:26:03.296+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:26:03.301+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:26:03.322+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.048 seconds
[2025-10-30T12:26:33.740+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:26:33.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:26:33.744+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:26:33.743+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:26:33.769+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:26:33.764+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:26:33.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:26:33.799+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.064 seconds
[2025-10-30T12:27:04.210+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:27:04.211+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:27:04.213+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:27:04.213+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:27:04.234+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:27:04.228+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:27:04.237+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:27:04.266+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.062 seconds
[2025-10-30T12:27:34.680+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:27:34.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:27:34.684+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:27:34.683+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:27:34.701+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:27:34.697+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:27:34.703+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:27:34.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.055 seconds
[2025-10-30T12:28:04.097+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:28:04.098+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:28:04.100+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:28:04.100+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:28:04.119+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:28:04.114+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:28:04.121+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:28:04.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.052 seconds
[2025-10-30T12:28:34.524+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:28:34.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:28:34.527+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:28:34.527+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:28:34.545+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:28:34.541+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:28:34.547+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:28:34.569+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.050 seconds
[2025-10-30T12:29:05.068+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:29:05.069+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:29:05.071+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:29:05.071+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:29:05.086+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:29:05.083+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:29:05.087+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:29:05.109+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.047 seconds
[2025-10-30T12:29:35.566+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:29:35.567+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:29:35.569+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:29:35.569+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:29:35.588+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:29:35.585+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:29:35.590+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:29:35.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.047 seconds
[2025-10-30T12:30:06.002+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:30:06.003+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:30:06.006+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:30:06.005+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:30:06.026+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:30:06.022+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:30:06.028+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:30:06.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.054 seconds
[2025-10-30T12:30:36.479+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:30:36.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:30:36.482+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:30:36.482+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:30:36.508+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:30:36.503+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:30:36.510+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:30:36.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.060 seconds
[2025-10-30T12:31:07.016+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:31:07.017+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:31:07.019+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:31:07.019+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:31:07.034+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:31:07.031+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:31:07.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:31:07.058+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.046 seconds
[2025-10-30T12:31:37.543+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:31:37.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:31:37.546+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:31:37.546+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:31:37.563+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:31:37.559+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:31:37.564+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:31:37.592+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.054 seconds
[2025-10-30T12:32:08.017+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:32:08.018+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:32:08.020+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:32:08.019+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:32:08.037+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:32:08.034+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:32:08.039+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:32:08.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.047 seconds
[2025-10-30T12:32:49.774+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:32:49.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:32:49.777+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:32:49.777+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:32:49.798+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:32:49.794+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:32:49.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:32:49.820+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.052 seconds
[2025-10-30T12:33:20.281+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:33:20.282+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:33:20.284+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:33:20.284+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:33:20.308+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:33:20.303+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:33:20.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:33:20.336+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.062 seconds
[2025-10-30T12:33:50.761+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:33:50.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:33:50.764+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:33:50.764+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:33:50.796+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:33:50.781+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:33:50.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:33:50.824+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.068 seconds
[2025-10-30T12:34:21.247+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:34:21.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:34:21.251+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:34:21.250+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:34:21.273+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:34:21.268+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:34:21.275+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:34:21.302+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.060 seconds
[2025-10-30T12:42:22.393+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:42:22.394+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:42:22.396+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:42:22.395+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:42:22.412+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:42:22.408+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:42:22.413+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:42:22.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.047 seconds
[2025-10-30T12:42:52.930+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:42:52.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:42:52.934+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:42:52.933+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:42:52.952+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:42:52.949+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:42:52.954+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:42:52.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.052 seconds
[2025-10-30T12:43:23.394+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:43:23.396+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:43:23.398+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:43:23.397+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:43:23.419+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:43:23.415+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:43:23.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:43:23.449+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.061 seconds
[2025-10-30T12:43:53.812+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:43:53.814+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:43:53.816+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:43:53.816+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:43:53.840+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:43:53.836+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:43:53.842+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:43:53.863+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.057 seconds
[2025-10-30T12:44:24.285+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:44:24.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:44:24.288+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:44:24.288+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:44:24.298+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:44:24.295+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:44:24.299+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:44:24.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.040 seconds
[2025-10-30T12:44:54.750+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:44:54.751+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:44:54.753+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:44:54.753+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:44:54.772+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:44:54.768+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:44:54.774+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:44:54.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.091 seconds
[2025-10-30T12:45:25.230+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:45:25.231+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:45:25.233+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:45:25.232+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:45:25.252+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:45:25.247+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:45:25.253+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:45:25.275+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.051 seconds
[2025-10-30T12:45:55.654+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:45:55.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:45:55.658+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:45:55.657+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:45:55.683+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:45:55.679+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:45:55.686+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:45:55.713+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.065 seconds
[2025-10-30T12:46:26.190+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:46:26.191+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:46:26.193+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:46:26.193+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:46:26.210+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:46:26.205+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:46:26.212+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:46:26.233+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.047 seconds
[2025-10-30T12:46:56.809+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:46:56.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:46:56.813+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:46:56.812+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:46:56.846+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:46:56.839+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:46:56.849+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:46:56.878+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.076 seconds
[2025-10-30T12:47:27.547+0000] {processor.py:161} INFO - Started process (PID=69) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:47:27.548+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:47:27.550+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:47:27.550+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:47:27.580+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:47:27.575+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:47:27.583+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:47:27.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.075 seconds
[2025-10-30T12:47:58.093+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:47:58.095+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:47:58.097+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:47:58.096+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:47:58.127+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:47:58.121+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:47:58.129+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:47:58.154+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.065 seconds
[2025-10-30T12:48:28.634+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:48:28.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:48:28.639+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:48:28.638+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:48:28.665+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:48:28.660+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:48:28.666+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:48:28.695+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.071 seconds
[2025-10-30T12:48:59.144+0000] {processor.py:161} INFO - Started process (PID=78) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:48:59.145+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:48:59.147+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:48:59.147+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:48:59.161+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:48:59.159+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:48:59.162+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:48:59.183+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.044 seconds
[2025-10-30T12:49:29.661+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:49:29.662+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:49:29.664+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:49:29.664+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:49:29.711+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:49:29.706+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:49:29.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:49:29.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.082 seconds
[2025-10-30T12:50:00.232+0000] {processor.py:161} INFO - Started process (PID=84) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:50:00.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:50:00.235+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:50:00.235+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:50:00.250+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:50:00.247+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:50:00.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:50:00.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.043 seconds
[2025-10-30T12:50:30.918+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:50:30.919+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:50:30.925+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:50:30.925+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:50:30.935+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:50:30.932+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:50:30.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:50:30.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.045 seconds
[2025-10-30T12:51:01.974+0000] {processor.py:161} INFO - Started process (PID=90) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:51:01.978+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:51:01.986+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:51:01.985+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:51:02.021+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:51:02.018+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:51:02.023+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:51:02.063+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.105 seconds
[2025-10-30T12:51:32.571+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:51:32.573+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:51:32.575+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:51:32.574+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:51:32.595+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:51:32.592+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:51:32.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:51:32.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.058 seconds
[2025-10-30T12:52:03.207+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:52:03.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:52:03.210+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:52:03.209+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:52:03.227+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:52:03.223+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:52:03.229+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:52:03.251+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.050 seconds
[2025-10-30T12:52:33.799+0000] {processor.py:161} INFO - Started process (PID=99) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:52:33.800+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:52:33.802+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:52:33.802+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:52:33.827+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:52:33.824+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:52:33.828+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:52:33.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.063 seconds
[2025-10-30T12:53:04.339+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:53:04.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:53:04.342+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:53:04.341+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:53:04.358+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:53:04.355+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:53:04.359+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:53:04.385+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.053 seconds
[2025-10-30T12:53:34.829+0000] {processor.py:161} INFO - Started process (PID=105) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:53:34.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:53:34.832+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:53:34.832+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:53:34.851+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:53:34.848+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:53:34.853+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:53:34.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.050 seconds
[2025-10-30T12:54:05.340+0000] {processor.py:161} INFO - Started process (PID=108) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:54:05.341+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:54:05.342+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:54:05.342+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:54:05.368+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:54:05.363+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:54:05.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:54:05.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.057 seconds
[2025-10-30T12:54:35.756+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:54:35.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:54:35.759+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:54:35.759+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:54:35.776+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:54:35.773+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:54:35.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:54:35.796+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.048 seconds
[2025-10-30T12:55:06.251+0000] {processor.py:161} INFO - Started process (PID=114) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:55:06.252+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:55:06.255+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:55:06.254+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:55:06.276+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:55:06.273+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:55:06.277+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:55:06.299+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.056 seconds
[2025-10-30T12:55:36.656+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:55:36.657+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:55:36.659+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:55:36.659+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:55:36.685+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:55:36.679+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:55:36.688+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:55:36.712+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.062 seconds
[2025-10-30T12:56:07.679+0000] {processor.py:161} INFO - Started process (PID=120) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:56:07.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:56:07.682+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:56:07.682+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:56:07.705+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:56:07.700+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:56:07.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:56:07.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.058 seconds
[2025-10-30T12:56:38.242+0000] {processor.py:161} INFO - Started process (PID=123) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:56:38.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:56:38.245+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:56:38.245+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:56:38.263+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:56:38.259+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:56:38.265+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:56:38.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.053 seconds
[2025-10-30T12:57:08.773+0000] {processor.py:161} INFO - Started process (PID=126) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:57:08.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:57:08.776+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:57:08.776+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:57:08.794+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:57:08.791+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:57:08.795+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:57:08.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.051 seconds
[2025-10-30T12:57:39.390+0000] {processor.py:161} INFO - Started process (PID=129) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:57:39.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:57:39.393+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:57:39.392+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:57:39.406+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:57:39.403+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:57:39.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:57:39.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.049 seconds
[2025-10-30T12:58:09.903+0000] {processor.py:161} INFO - Started process (PID=132) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:58:09.904+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:58:09.906+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:58:09.906+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:58:09.923+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:58:09.920+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:58:09.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:58:09.946+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.048 seconds
[2025-10-30T12:58:40.373+0000] {processor.py:161} INFO - Started process (PID=135) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:58:40.374+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:58:40.376+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:58:40.375+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:58:40.391+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:58:40.389+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:58:40.392+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:58:40.414+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.047 seconds
[2025-10-30T12:59:10.767+0000] {processor.py:161} INFO - Started process (PID=138) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:59:10.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:59:10.770+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:59:10.770+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:59:10.785+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:59:10.782+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:59:10.785+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:59:10.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.045 seconds
[2025-10-30T12:59:41.243+0000] {processor.py:161} INFO - Started process (PID=141) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:59:41.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T12:59:41.246+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:59:41.246+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:59:41.267+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:59:41.264+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:59:41.268+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T12:59:41.292+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.057 seconds
[2025-10-30T13:00:11.698+0000] {processor.py:161} INFO - Started process (PID=144) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:00:11.699+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T13:00:11.701+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:00:11.700+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:00:11.715+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:00:11.712+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:00:11.716+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:00:11.740+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.049 seconds
[2025-10-30T13:00:42.218+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:00:42.220+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T13:00:42.222+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:00:42.222+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:00:42.254+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:00:42.246+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:00:42.257+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:00:42.279+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.067 seconds
[2025-10-30T13:01:12.748+0000] {processor.py:161} INFO - Started process (PID=150) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:01:12.749+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T13:01:12.751+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:01:12.751+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:01:12.790+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:01:12.785+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:01:12.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:01:12.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.071 seconds
[2025-10-30T13:01:43.264+0000] {processor.py:161} INFO - Started process (PID=153) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:01:43.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T13:01:43.267+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:01:43.267+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:01:43.288+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:01:43.284+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:01:43.290+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:01:43.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.058 seconds
[2025-10-30T13:02:13.787+0000] {processor.py:161} INFO - Started process (PID=156) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:02:13.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T13:02:13.790+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:02:13.790+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:02:13.805+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:02:13.802+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:02:13.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:02:13.829+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.047 seconds
[2025-10-30T13:02:44.286+0000] {processor.py:161} INFO - Started process (PID=159) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:02:44.287+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T13:02:44.289+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:02:44.289+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:02:44.314+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:02:44.309+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:02:44.315+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:02:44.339+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.062 seconds
[2025-10-30T13:03:14.818+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:03:14.820+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T13:03:14.822+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:03:14.821+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:03:14.844+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:03:14.839+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:03:14.846+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:03:14.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.062 seconds
[2025-10-30T13:03:45.312+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:03:45.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T13:03:45.315+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:03:45.315+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:03:45.363+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:03:45.357+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:03:45.365+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:03:45.387+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.080 seconds
[2025-10-30T13:04:15.805+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:04:15.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T13:04:15.808+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:04:15.808+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:04:15.830+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:04:15.827+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:04:15.831+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:04:15.855+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.056 seconds
[2025-10-30T13:04:46.334+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:04:46.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T13:04:46.336+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:04:46.336+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:04:46.356+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:04:46.352+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:04:46.358+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:04:46.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.053 seconds
[2025-10-30T13:05:16.859+0000] {processor.py:161} INFO - Started process (PID=174) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:05:16.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T13:05:16.862+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:05:16.861+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:05:16.878+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:05:16.874+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:05:16.879+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:05:16.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.046 seconds
[2025-10-30T13:05:47.378+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:05:47.379+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T13:05:47.381+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:05:47.380+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:05:47.398+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:05:47.394+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:05:47.400+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:05:47.428+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.055 seconds
[2025-10-30T13:06:17.992+0000] {processor.py:161} INFO - Started process (PID=180) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:06:17.996+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T13:06:18.001+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:06:18.000+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:06:18.196+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:06:18.163+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:06:18.204+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:06:18.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.260 seconds
[2025-10-30T13:06:48.416+0000] {processor.py:161} INFO - Started process (PID=183) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:06:48.417+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T13:06:48.419+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:06:48.418+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:06:48.445+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:06:48.443+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:06:48.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:06:48.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.058 seconds
[2025-10-30T13:07:18.891+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:07:18.892+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T13:07:18.894+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:07:18.893+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:07:18.910+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:07:18.907+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:07:18.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:07:18.935+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.052 seconds
[2025-10-30T13:07:49.427+0000] {processor.py:161} INFO - Started process (PID=189) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:07:49.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T13:07:49.430+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:07:49.429+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:07:49.445+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:07:49.442+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:07:49.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:07:49.471+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.051 seconds
[2025-10-30T13:08:19.920+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:08:19.921+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_execution_dag.py for tasks to queue
[2025-10-30T13:08:19.923+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:08:19.923+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:08:19.939+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:08:19.935+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_execution_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_execution_dag.py", line 8, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:08:19.940+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_execution_dag.py
[2025-10-30T13:08:19.962+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_execution_dag.py took 0.046 seconds
