[2025-10-30T12:26:03.198+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:26:03.199+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:26:03.200+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:26:03.200+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:26:03.217+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:26:03.213+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:26:03.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:26:03.240+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.048 seconds
[2025-10-30T12:26:33.619+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:26:33.621+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:26:33.626+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:26:33.625+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:26:33.644+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:26:33.640+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:26:33.646+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:26:33.688+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.083 seconds
[2025-10-30T12:27:04.110+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:27:04.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:27:04.114+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:27:04.114+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:27:04.131+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:27:04.128+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:27:04.134+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:27:04.171+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.068 seconds
[2025-10-30T12:27:34.594+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:27:34.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:27:34.597+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:27:34.597+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:27:34.617+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:27:34.611+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:27:34.619+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:27:34.647+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.058 seconds
[2025-10-30T12:28:04.007+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:28:04.008+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:28:04.010+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:28:04.010+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:28:04.033+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:28:04.027+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:28:04.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:28:04.063+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.065 seconds
[2025-10-30T12:28:34.438+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:28:34.439+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:28:34.441+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:28:34.441+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:28:34.457+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:28:34.454+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:28:34.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:28:34.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.050 seconds
[2025-10-30T12:29:04.960+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:29:04.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:29:04.963+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:29:04.963+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:29:04.980+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:29:04.976+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:29:04.981+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:29:05.002+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.047 seconds
[2025-10-30T12:29:35.474+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:29:35.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:29:35.477+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:29:35.477+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:29:35.504+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:29:35.494+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:29:35.505+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:29:35.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.059 seconds
[2025-10-30T12:30:05.929+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:30:05.929+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:30:05.931+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:30:05.931+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:30:05.953+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:30:05.948+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:30:05.954+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:30:05.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.054 seconds
[2025-10-30T12:30:36.395+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:30:36.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:30:36.398+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:30:36.398+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:30:36.410+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:30:36.407+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:30:36.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:30:36.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.044 seconds
[2025-10-30T12:31:06.899+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:31:06.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:31:06.901+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:31:06.901+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:31:06.914+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:31:06.910+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:31:06.915+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:31:06.939+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.046 seconds
[2025-10-30T12:31:37.457+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:31:37.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:31:37.460+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:31:37.459+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:31:37.480+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:31:37.474+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:31:37.482+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:31:37.511+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.059 seconds
[2025-10-30T12:32:07.938+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:32:07.939+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:32:07.941+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:32:07.940+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:32:07.958+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:32:07.954+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:32:07.960+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:32:07.982+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.049 seconds
[2025-10-30T12:32:49.698+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:32:49.699+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:32:49.701+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:32:49.701+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:32:49.718+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:32:49.713+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:32:49.720+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:32:49.743+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.050 seconds
[2025-10-30T12:33:20.171+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:33:20.172+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:33:20.175+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:33:20.174+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:33:20.199+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:33:20.193+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:33:20.201+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:33:20.232+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.068 seconds
[2025-10-30T12:33:50.664+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:33:50.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:33:50.668+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:33:50.667+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:33:50.681+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:33:50.678+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:33:50.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:33:50.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.051 seconds
[2025-10-30T12:34:21.163+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:34:21.164+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:34:21.166+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:34:21.165+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:34:21.183+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:34:21.179+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:34:21.185+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:34:21.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.048 seconds
[2025-10-30T12:42:22.294+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:42:22.295+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:42:22.297+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:42:22.297+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:42:22.318+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:42:22.313+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:42:22.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:42:22.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.052 seconds
[2025-10-30T12:42:52.818+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:42:52.818+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:42:52.823+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:42:52.823+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:42:52.844+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:42:52.839+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:42:52.846+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:42:52.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.064 seconds
[2025-10-30T12:43:23.292+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:43:23.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:43:23.296+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:43:23.296+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:43:23.316+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:43:23.310+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:43:23.318+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:43:23.353+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.069 seconds
[2025-10-30T12:43:53.734+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:43:53.735+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:43:53.738+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:43:53.738+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:43:53.758+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:43:53.753+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:43:53.760+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:43:53.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.058 seconds
[2025-10-30T12:44:24.160+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:44:24.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:44:24.162+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:44:24.162+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:44:24.174+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:44:24.171+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:44:24.175+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:44:24.195+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.039 seconds
[2025-10-30T12:44:54.663+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:44:54.664+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:44:54.666+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:44:54.666+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:44:54.684+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:44:54.680+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:44:54.686+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:44:54.711+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.052 seconds
[2025-10-30T12:45:25.127+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:45:25.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:45:25.131+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:45:25.130+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:45:25.151+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:45:25.146+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:45:25.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:45:25.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.057 seconds
[2025-10-30T12:45:55.565+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:45:55.566+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:45:55.568+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:45:55.568+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:45:55.590+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:45:55.585+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:45:55.592+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:45:55.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.066 seconds
[2025-10-30T12:46:26.034+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:46:26.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:46:26.037+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:46:26.036+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:46:26.057+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:46:26.053+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:46:26.059+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:46:26.145+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.117 seconds
[2025-10-30T12:46:56.671+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:46:56.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:46:56.675+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:46:56.674+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:46:56.705+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:46:56.698+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:46:56.707+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:46:56.742+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.080 seconds
[2025-10-30T12:47:27.440+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:47:27.441+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:47:27.443+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:47:27.442+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:47:27.475+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:47:27.468+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:47:27.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:47:27.502+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.068 seconds
[2025-10-30T12:47:57.974+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:47:57.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:47:57.983+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:47:57.983+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:47:58.009+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:47:58.003+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:47:58.010+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:47:58.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.083 seconds
[2025-10-30T12:48:28.492+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:48:28.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:48:28.495+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:48:28.495+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:48:28.508+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:48:28.505+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:48:28.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:48:28.530+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.043 seconds
[2025-10-30T12:48:59.023+0000] {processor.py:161} INFO - Started process (PID=77) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:48:59.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:48:59.026+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:48:59.026+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:48:59.036+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:48:59.034+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:48:59.037+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:48:59.057+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.039 seconds
[2025-10-30T12:49:29.604+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:49:29.605+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:49:29.607+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:49:29.607+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:49:29.622+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:49:29.619+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:49:29.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:49:29.651+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.055 seconds
[2025-10-30T12:50:00.130+0000] {processor.py:161} INFO - Started process (PID=83) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:50:00.131+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:50:00.133+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:50:00.132+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:50:00.143+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:50:00.140+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:50:00.144+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:50:00.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.038 seconds
[2025-10-30T12:50:30.796+0000] {processor.py:161} INFO - Started process (PID=86) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:50:30.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:50:30.799+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:50:30.798+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:50:30.810+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:50:30.808+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:50:30.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:50:30.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.043 seconds
[2025-10-30T12:51:01.576+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:51:01.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:51:01.579+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:51:01.579+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:51:01.840+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:51:01.827+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:51:01.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:51:01.886+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.315 seconds
[2025-10-30T12:51:32.460+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:51:32.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:51:32.464+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:51:32.463+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:51:32.483+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:51:32.479+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:51:32.485+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:51:32.507+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.052 seconds
[2025-10-30T12:52:03.113+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:52:03.116+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:52:03.119+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:52:03.118+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:52:03.147+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:52:03.143+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:52:03.148+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:52:03.174+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.069 seconds
[2025-10-30T12:52:33.654+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:52:33.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:52:33.663+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:52:33.662+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:52:33.689+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:52:33.679+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:52:33.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:52:33.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.097 seconds
[2025-10-30T12:53:04.236+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:53:04.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:53:04.241+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:53:04.241+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:53:04.257+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:53:04.254+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:53:04.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:53:04.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.057 seconds
[2025-10-30T12:53:34.731+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:53:34.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:53:34.733+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:53:34.733+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:53:34.754+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:53:34.749+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:53:34.755+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:53:34.780+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.055 seconds
[2025-10-30T12:54:05.262+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:54:05.263+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:54:05.267+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:54:05.267+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:54:05.291+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:54:05.285+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:54:05.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:54:05.313+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.056 seconds
[2025-10-30T12:54:35.656+0000] {processor.py:161} INFO - Started process (PID=110) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:54:35.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:54:35.658+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:54:35.658+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:54:35.673+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:54:35.668+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:54:35.674+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:54:35.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.043 seconds
[2025-10-30T12:55:06.138+0000] {processor.py:161} INFO - Started process (PID=113) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:55:06.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:55:06.141+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:55:06.140+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:55:06.151+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:55:06.148+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:55:06.153+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:55:06.174+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.041 seconds
[2025-10-30T12:55:36.561+0000] {processor.py:161} INFO - Started process (PID=116) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:55:36.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:55:36.564+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:55:36.564+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:55:36.583+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:55:36.580+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:55:36.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:55:36.611+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.055 seconds
[2025-10-30T12:56:07.577+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:56:07.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:56:07.581+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:56:07.580+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:56:07.599+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:56:07.595+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:56:07.600+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:56:07.631+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.060 seconds
[2025-10-30T12:56:38.110+0000] {processor.py:161} INFO - Started process (PID=122) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:56:38.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:56:38.113+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:56:38.113+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:56:38.126+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:56:38.123+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:56:38.128+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:56:38.150+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.045 seconds
[2025-10-30T12:57:08.675+0000] {processor.py:161} INFO - Started process (PID=125) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:57:08.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:57:08.678+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:57:08.678+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:57:08.691+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:57:08.687+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:57:08.692+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:57:08.714+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.044 seconds
[2025-10-30T12:57:39.266+0000] {processor.py:161} INFO - Started process (PID=128) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:57:39.267+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:57:39.269+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:57:39.269+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:57:39.280+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:57:39.277+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:57:39.281+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:57:39.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.039 seconds
[2025-10-30T12:58:09.818+0000] {processor.py:161} INFO - Started process (PID=131) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:58:09.819+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:58:09.822+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:58:09.821+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:58:09.845+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:58:09.840+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:58:09.847+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:58:09.867+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.057 seconds
[2025-10-30T12:58:40.269+0000] {processor.py:161} INFO - Started process (PID=134) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:58:40.270+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:58:40.271+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:58:40.271+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:58:40.282+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:58:40.279+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:58:40.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:58:40.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.039 seconds
[2025-10-30T12:59:10.703+0000] {processor.py:161} INFO - Started process (PID=137) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:59:10.704+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:59:10.705+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:59:10.705+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:59:10.719+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:59:10.716+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:59:10.720+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:59:10.740+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.041 seconds
[2025-10-30T12:59:41.126+0000] {processor.py:161} INFO - Started process (PID=140) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:59:41.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T12:59:41.130+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:59:41.129+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:59:41.141+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:59:41.139+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T12:59:41.142+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T12:59:41.162+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.040 seconds
[2025-10-30T13:00:11.563+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:00:11.564+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T13:00:11.567+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:00:11.566+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:00:11.590+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:00:11.587+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T13:00:11.591+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:00:11.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.055 seconds
[2025-10-30T13:00:42.099+0000] {processor.py:161} INFO - Started process (PID=146) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:00:42.100+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T13:00:42.102+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:00:42.101+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:00:42.113+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:00:42.110+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T13:00:42.117+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:00:42.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.041 seconds
[2025-10-30T13:01:12.638+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:01:12.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T13:01:12.641+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:01:12.641+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:01:12.655+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:01:12.652+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T13:01:12.657+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:01:12.678+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.046 seconds
[2025-10-30T13:01:43.152+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:01:43.153+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T13:01:43.155+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:01:43.155+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:01:43.174+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:01:43.170+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T13:01:43.175+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:01:43.197+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.052 seconds
[2025-10-30T13:02:13.660+0000] {processor.py:161} INFO - Started process (PID=155) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:02:13.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T13:02:13.663+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:02:13.663+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:02:13.683+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:02:13.678+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T13:02:13.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:02:13.707+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.053 seconds
[2025-10-30T13:02:44.161+0000] {processor.py:161} INFO - Started process (PID=158) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:02:44.162+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T13:02:44.164+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:02:44.164+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:02:44.175+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:02:44.173+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T13:02:44.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:02:44.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.041 seconds
[2025-10-30T13:03:14.710+0000] {processor.py:161} INFO - Started process (PID=161) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:03:14.711+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T13:03:14.712+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:03:14.712+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:03:14.737+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:03:14.728+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T13:03:14.738+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:03:14.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.062 seconds
[2025-10-30T13:03:45.218+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:03:45.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T13:03:45.221+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:03:45.220+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:03:45.236+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:03:45.232+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T13:03:45.237+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:03:45.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.046 seconds
[2025-10-30T13:04:15.709+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:04:15.710+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T13:04:15.712+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:04:15.711+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:04:15.735+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:04:15.732+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T13:04:15.736+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:04:15.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.053 seconds
[2025-10-30T13:04:46.184+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:04:46.185+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T13:04:46.187+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:04:46.187+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:04:46.199+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:04:46.196+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T13:04:46.200+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:04:46.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.043 seconds
[2025-10-30T13:05:16.763+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:05:16.764+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T13:05:16.766+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:05:16.766+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:05:16.788+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:05:16.784+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T13:05:16.789+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:05:16.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.053 seconds
[2025-10-30T13:05:47.288+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:05:47.289+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T13:05:47.292+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:05:47.292+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:05:47.311+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:05:47.306+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T13:05:47.312+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:05:47.339+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.055 seconds
[2025-10-30T13:06:17.719+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:06:17.720+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T13:06:17.722+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:06:17.721+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:06:17.738+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:06:17.735+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T13:06:17.739+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:06:17.762+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.049 seconds
[2025-10-30T13:06:48.318+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:06:48.319+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T13:06:48.321+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:06:48.321+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:06:48.332+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:06:48.329+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T13:06:48.334+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:06:48.355+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.042 seconds
[2025-10-30T13:07:18.786+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:07:18.787+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T13:07:18.789+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:07:18.788+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:07:18.799+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:07:18.797+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T13:07:18.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:07:18.820+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.039 seconds
[2025-10-30T13:07:49.289+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:07:49.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T13:07:49.293+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:07:49.292+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:07:49.318+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:07:49.314+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T13:07:49.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:07:49.345+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.066 seconds
[2025-10-30T13:08:19.857+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:08:19.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_schedule_sync_dag.py for tasks to queue
[2025-10-30T13:08:19.859+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:08:19.859+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:08:19.871+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:08:19.868+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_schedule_sync_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_schedule_sync_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-30T13:08:19.872+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_schedule_sync_dag.py
[2025-10-30T13:08:19.892+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_schedule_sync_dag.py took 0.041 seconds
