[2025-10-30T12:26:03.191+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:26:03.192+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:26:03.195+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:26:03.194+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:26:03.213+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:26:03.209+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:26:03.215+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:26:03.240+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.055 seconds
[2025-10-30T12:26:33.604+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:26:33.605+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:26:33.609+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:26:33.609+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:26:33.627+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:26:33.623+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:26:33.628+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:26:33.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.086 seconds
[2025-10-30T12:27:04.099+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:27:04.100+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:27:04.104+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:27:04.103+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:27:04.128+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:27:04.124+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:27:04.130+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:27:04.171+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.083 seconds
[2025-10-30T12:27:34.584+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:27:34.585+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:27:34.587+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:27:34.586+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:27:34.606+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:27:34.602+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:27:34.608+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:27:34.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.061 seconds
[2025-10-30T12:28:03.990+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:28:03.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:28:03.994+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:28:03.994+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:28:04.021+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:28:04.015+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:28:04.024+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:28:04.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.072 seconds
[2025-10-30T12:28:34.433+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:28:34.434+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:28:34.437+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:28:34.436+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:28:34.456+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:28:34.452+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:28:34.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:28:34.483+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.057 seconds
[2025-10-30T12:29:04.953+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:29:04.953+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:29:04.955+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:29:04.955+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:29:04.967+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:29:04.964+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:29:04.968+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:29:04.994+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.047 seconds
[2025-10-30T12:29:35.457+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:29:35.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:29:35.466+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:29:35.466+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:29:35.477+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:29:35.474+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:29:35.478+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:29:35.511+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.059 seconds
[2025-10-30T12:30:05.921+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:30:05.922+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:30:05.924+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:30:05.923+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:30:05.941+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:30:05.937+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:30:05.942+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:30:05.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.053 seconds
[2025-10-30T12:30:36.385+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:30:36.386+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:30:36.387+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:30:36.387+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:30:36.401+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:30:36.398+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:30:36.402+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:30:36.428+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.047 seconds
[2025-10-30T12:31:06.890+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:31:06.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:31:06.893+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:31:06.893+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:31:06.905+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:31:06.902+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:31:06.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:31:06.933+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.048 seconds
[2025-10-30T12:31:37.448+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:31:37.448+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:31:37.450+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:31:37.450+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:31:37.469+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:31:37.464+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:31:37.470+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:31:37.506+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.064 seconds
[2025-10-30T12:32:07.928+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:32:07.929+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:32:07.930+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:32:07.930+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:32:07.949+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:32:07.944+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:32:07.950+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:32:07.975+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.052 seconds
[2025-10-30T12:32:49.687+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:32:49.688+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:32:49.691+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:32:49.690+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:32:49.711+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:32:49.706+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:32:49.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:32:49.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.055 seconds
[2025-10-30T12:33:20.159+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:33:20.160+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:33:20.164+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:33:20.164+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:33:20.192+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:33:20.186+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:33:20.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:33:20.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.075 seconds
[2025-10-30T12:33:50.652+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:33:50.652+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:33:50.655+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:33:50.654+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:33:50.671+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:33:50.666+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:33:50.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:33:50.700+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.059 seconds
[2025-10-30T12:34:21.159+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:34:21.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:34:21.161+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:34:21.161+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:34:21.179+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:34:21.175+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:34:21.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:34:21.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.051 seconds
[2025-10-30T12:42:22.285+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:42:22.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:42:22.289+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:42:22.288+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:42:22.313+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:42:22.308+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:42:22.315+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:42:22.340+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.064 seconds
[2025-10-30T12:42:52.801+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:42:52.802+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:42:52.805+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:42:52.804+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:42:52.831+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:42:52.826+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:42:52.833+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:42:52.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.077 seconds
[2025-10-30T12:43:23.282+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:43:23.283+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:43:23.285+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:43:23.285+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:43:23.306+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:43:23.301+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:43:23.307+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:43:23.345+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.069 seconds
[2025-10-30T12:43:53.723+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:43:53.724+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:43:53.725+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:43:53.725+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:43:53.743+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:43:53.739+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:43:53.745+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:43:53.772+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.055 seconds
[2025-10-30T12:44:24.154+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:44:24.154+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:44:24.156+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:44:24.156+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:44:24.169+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:44:24.166+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:44:24.170+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:44:24.191+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.042 seconds
[2025-10-30T12:44:54.654+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:44:54.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:44:54.657+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:44:54.656+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:44:54.671+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:44:54.666+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:44:54.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:44:54.703+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.053 seconds
[2025-10-30T12:45:25.122+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:45:25.123+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:45:25.125+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:45:25.125+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:45:25.145+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:45:25.141+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:45:25.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:45:25.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.058 seconds
[2025-10-30T12:45:55.553+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:45:55.554+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:45:55.557+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:45:55.556+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:45:55.578+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:45:55.573+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:45:55.580+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:45:55.610+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.064 seconds
[2025-10-30T12:46:26.023+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:46:26.026+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:46:26.028+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:46:26.028+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:46:26.056+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:46:26.052+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:46:26.057+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:46:26.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.127 seconds
[2025-10-30T12:46:56.657+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:46:56.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:46:56.662+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:46:56.661+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:46:56.692+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:46:56.686+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:46:56.694+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:46:56.727+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.076 seconds
[2025-10-30T12:47:27.427+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:47:27.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:47:27.430+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:47:27.429+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:47:27.453+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:47:27.448+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:47:27.455+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:47:27.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.055 seconds
[2025-10-30T12:47:57.960+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:47:57.962+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:47:57.967+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:47:57.967+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:47:58.003+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:47:57.996+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:47:58.006+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:47:58.052+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.099 seconds
[2025-10-30T12:48:28.486+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:48:28.487+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:48:28.490+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:48:28.489+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:48:28.504+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:48:28.501+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:48:28.505+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:48:28.526+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.045 seconds
[2025-10-30T12:48:59.017+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:48:59.018+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:48:59.019+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:48:59.019+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:48:59.031+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:48:59.028+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:48:59.032+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:48:59.053+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.040 seconds
[2025-10-30T12:49:29.594+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:49:29.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:49:29.597+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:49:29.597+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:49:29.612+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:49:29.609+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:49:29.614+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:49:29.635+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.048 seconds
[2025-10-30T12:50:00.122+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:50:00.123+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:50:00.125+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:50:00.124+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:50:00.136+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:50:00.134+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:50:00.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:50:00.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.042 seconds
[2025-10-30T12:50:30.794+0000] {processor.py:161} INFO - Started process (PID=85) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:50:30.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:50:30.797+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:50:30.797+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:50:30.810+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:50:30.807+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:50:30.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:50:30.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.043 seconds
[2025-10-30T12:51:01.575+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:51:01.576+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:51:01.578+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:51:01.578+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:51:01.840+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:51:01.828+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:51:01.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:51:01.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.315 seconds
[2025-10-30T12:51:32.453+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:51:32.455+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:51:32.457+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:51:32.457+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:51:32.479+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:51:32.475+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:51:32.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:51:32.507+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.061 seconds
[2025-10-30T12:52:03.107+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:52:03.109+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:52:03.112+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:52:03.111+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:52:03.144+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:52:03.139+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:52:03.145+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:52:03.170+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.070 seconds
[2025-10-30T12:52:33.628+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:52:33.630+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:52:33.637+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:52:33.636+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:52:33.663+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:52:33.657+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:52:33.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:52:33.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.112 seconds
[2025-10-30T12:53:04.223+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:53:04.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:53:04.228+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:53:04.227+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:53:04.250+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:53:04.246+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:53:04.252+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:53:04.275+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.065 seconds
[2025-10-30T12:53:34.720+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:53:34.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:53:34.723+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:53:34.722+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:53:34.743+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:53:34.738+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:53:34.745+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:53:34.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.052 seconds
[2025-10-30T12:54:05.252+0000] {processor.py:161} INFO - Started process (PID=106) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:54:05.253+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:54:05.255+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:54:05.254+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:54:05.278+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:54:05.274+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:54:05.281+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:54:05.305+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.058 seconds
[2025-10-30T12:54:35.647+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:54:35.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:54:35.649+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:54:35.649+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:54:35.660+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:54:35.657+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:54:35.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:54:35.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.043 seconds
[2025-10-30T12:55:06.133+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:55:06.133+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:55:06.135+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:55:06.135+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:55:06.147+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:55:06.145+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:55:06.148+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:55:06.170+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.042 seconds
[2025-10-30T12:55:36.554+0000] {processor.py:161} INFO - Started process (PID=115) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:55:36.555+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:55:36.557+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:55:36.557+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:55:36.580+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:55:36.575+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:55:36.581+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:55:36.608+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.059 seconds
[2025-10-30T12:56:07.573+0000] {processor.py:161} INFO - Started process (PID=118) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:56:07.574+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:56:07.577+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:56:07.577+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:56:07.598+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:56:07.594+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:56:07.600+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:56:07.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.067 seconds
[2025-10-30T12:56:38.102+0000] {processor.py:161} INFO - Started process (PID=121) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:56:38.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:56:38.104+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:56:38.104+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:56:38.118+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:56:38.114+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:56:38.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:56:38.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.048 seconds
[2025-10-30T12:57:08.664+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:57:08.664+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:57:08.666+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:57:08.666+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:57:08.681+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:57:08.677+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:57:08.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:57:08.706+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.048 seconds
[2025-10-30T12:57:39.260+0000] {processor.py:161} INFO - Started process (PID=127) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:57:39.260+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:57:39.262+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:57:39.262+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:57:39.275+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:57:39.272+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:57:39.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:57:39.296+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.046 seconds
[2025-10-30T12:58:09.805+0000] {processor.py:161} INFO - Started process (PID=130) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:58:09.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:58:09.809+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:58:09.809+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:58:09.836+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:58:09.831+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:58:09.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:58:09.862+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.063 seconds
[2025-10-30T12:58:40.266+0000] {processor.py:161} INFO - Started process (PID=133) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:58:40.267+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:58:40.269+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:58:40.268+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:58:40.280+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:58:40.277+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:58:40.281+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:58:40.302+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.041 seconds
[2025-10-30T12:59:10.697+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:59:10.698+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:59:10.700+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:59:10.699+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:59:10.712+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:59:10.708+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:59:10.713+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:59:10.733+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.041 seconds
[2025-10-30T12:59:41.118+0000] {processor.py:161} INFO - Started process (PID=139) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:59:41.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T12:59:41.121+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:59:41.121+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:59:41.134+0000] {logging_mixin.py:188} INFO - [2025-10-30T12:59:41.131+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T12:59:41.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T12:59:41.157+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.044 seconds
[2025-10-30T13:00:11.559+0000] {processor.py:161} INFO - Started process (PID=142) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:00:11.560+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:00:11.562+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:00:11.562+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:00:11.585+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:00:11.573+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:00:11.586+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:00:11.607+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.053 seconds
[2025-10-30T13:00:42.098+0000] {processor.py:161} INFO - Started process (PID=145) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:00:42.099+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:00:42.101+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:00:42.100+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:00:42.111+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:00:42.109+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:00:42.113+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:00:42.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.045 seconds
[2025-10-30T13:01:12.632+0000] {processor.py:161} INFO - Started process (PID=148) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:01:12.633+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:01:12.635+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:01:12.634+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:01:12.648+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:01:12.645+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:01:12.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:01:12.676+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.050 seconds
[2025-10-30T13:01:43.140+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:01:43.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:01:43.144+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:01:43.143+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:01:43.162+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:01:43.158+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:01:43.165+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:01:43.191+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.056 seconds
[2025-10-30T13:02:13.650+0000] {processor.py:161} INFO - Started process (PID=154) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:02:13.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:02:13.653+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:02:13.652+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:02:13.672+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:02:13.668+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:02:13.674+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:02:13.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.055 seconds
[2025-10-30T13:02:44.161+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:02:44.162+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:02:44.164+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:02:44.164+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:02:44.175+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:02:44.173+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:02:44.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:02:44.197+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.044 seconds
[2025-10-30T13:03:14.707+0000] {processor.py:161} INFO - Started process (PID=160) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:03:14.707+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:03:14.709+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:03:14.709+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:03:14.728+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:03:14.723+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:03:14.730+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:03:14.758+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.056 seconds
[2025-10-30T13:03:45.180+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:03:45.181+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:03:45.183+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:03:45.182+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:03:45.225+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:03:45.222+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:03:45.226+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:03:45.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.085 seconds
[2025-10-30T13:04:15.702+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:04:15.703+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:04:15.706+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:04:15.705+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:04:15.728+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:04:15.719+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:04:15.729+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:04:15.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.057 seconds
[2025-10-30T13:04:46.184+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:04:46.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:04:46.186+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:04:46.186+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:04:46.199+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:04:46.196+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:04:46.200+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:04:46.221+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.045 seconds
[2025-10-30T13:05:16.756+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:05:16.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:05:16.759+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:05:16.759+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:05:16.779+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:05:16.775+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:05:16.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:05:16.808+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.057 seconds
[2025-10-30T13:05:47.283+0000] {processor.py:161} INFO - Started process (PID=175) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:05:47.284+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:05:47.287+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:05:47.286+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:05:47.308+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:05:47.302+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:05:47.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:05:47.338+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.062 seconds
[2025-10-30T13:06:17.710+0000] {processor.py:161} INFO - Started process (PID=178) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:06:17.711+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:06:17.713+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:06:17.713+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:06:17.726+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:06:17.722+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:06:17.727+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:06:17.750+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.045 seconds
[2025-10-30T13:06:48.311+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:06:48.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:06:48.314+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:06:48.313+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:06:48.325+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:06:48.322+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:06:48.326+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:06:48.348+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.044 seconds
[2025-10-30T13:07:18.779+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:07:18.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:07:18.782+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:07:18.781+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:07:18.792+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:07:18.790+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:07:18.793+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:07:18.817+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.042 seconds
[2025-10-30T13:07:49.281+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:07:49.283+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:07:49.287+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:07:49.287+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:07:49.317+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:07:49.310+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:07:49.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:07:49.344+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.074 seconds
[2025-10-30T13:08:19.849+0000] {processor.py:161} INFO - Started process (PID=190) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:08:19.850+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:08:19.852+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:08:19.852+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:08:19.864+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:08:19.861+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:08:19.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:08:19.889+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.046 seconds
[2025-10-30T13:08:50.326+0000] {processor.py:161} INFO - Started process (PID=193) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:08:50.327+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:08:50.329+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:08:50.329+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:08:50.340+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:08:50.337+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:08:50.341+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:08:50.362+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.044 seconds
[2025-10-30T13:09:20.762+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:09:20.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:09:20.765+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:09:20.765+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:09:20.776+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:09:20.774+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:09:20.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:09:20.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.043 seconds
[2025-10-30T13:09:51.225+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:09:51.226+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/schedule_dag_generator.py for tasks to queue
[2025-10-30T13:09:51.228+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:09:51.228+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:09:51.238+0000] {logging_mixin.py:188} INFO - [2025-10-30T13:09:51.236+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/schedule_dag_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/schedule_dag_generator.py", line 12, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-30T13:09:51.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/schedule_dag_generator.py
[2025-10-30T13:09:51.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/schedule_dag_generator.py took 0.043 seconds
